services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: us-east-1

    command:
      - server
      - /data
      - --console-address
      - ":9001"
    volumes:
      - minio:/data

volumes:
  minio:
    driver: local
